package coakka_v2_connector

import (
	"fmt"
	"strings"
)

type MessageKind int32

const (
	MessageKindUnspecified MessageKind = 0
	MessageKindRequest     MessageKind = 1
	MessageKindResponse    MessageKind = 2
	MessageKindEvent       MessageKind = 3
)

type BusinessStatus int32

const (
	BusinessStatusUnspecified BusinessStatus = 0
	BusinessStatusOK          BusinessStatus = 1
	BusinessStatusError       BusinessStatus = 2
)

type DeliveryHint int32

const (
	DeliveryHintUnspecified   DeliveryHint = 0
	DeliveryHintRouterDefault DeliveryHint = 1
	DeliveryHintPreferLocal   DeliveryHint = 2
	DeliveryHintRequireLocal  DeliveryHint = 3
	DeliveryHintRequireRemote DeliveryHint = 4
)

type PayloadFormat int32

const (
	PayloadFormatUnspecified PayloadFormat = 0
	PayloadFormatJSON        PayloadFormat = 1
	PayloadFormatProtobuf    PayloadFormat = 2
	PayloadFormatThrift      PayloadFormat = 3
	PayloadFormatMsgpack     PayloadFormat = 4
	PayloadFormatText        PayloadFormat = 5
	PayloadFormatPlainText   PayloadFormat = PayloadFormatText
	PayloadFormatBinary      PayloadFormat = 6
)

func (f PayloadFormat) String() string {
	switch f {
	case PayloadFormatJSON:
		return "JSON"
	case PayloadFormatProtobuf:
		return "PROTOBUF"
	case PayloadFormatThrift:
		return "THRIFT"
	case PayloadFormatMsgpack:
		return "MSGPACK"
	case PayloadFormatText:
		return "TEXT"
	case PayloadFormatBinary:
		return "BINARY"
	default:
		return "UNSPECIFIED"
	}
}

// DeadletterReason identifies why the runtime could not complete delivery.
// Values are stable across connector languages and may be persisted in
// diagnostics. Callers should retain unknown numeric values when forwarding a
// deadletter so newer runtime reasons remain observable.
type DeadletterReason int32

const (
	DeadletterReasonUnspecified           DeadletterReason = 0
	DeadletterReasonNoActiveSnapshot      DeadletterReason = 1
	DeadletterReasonRouteMiss             DeadletterReason = 2
	DeadletterReasonNoResponsibleHost     DeadletterReason = 3
	DeadletterReasonQueueRejected         DeadletterReason = 4
	DeadletterReasonLocalHandoffFailed    DeadletterReason = 5
	DeadletterReasonDeliveryFailed        DeadletterReason = 6
	DeadletterReasonTransportSendFailed   DeadletterReason = 7
	DeadletterReasonRuntimeStopped        DeadletterReason = 8
	DeadletterReasonInvalidEnvelope       DeadletterReason = 9
	DeadletterReasonEndpointUnavailable   DeadletterReason = 10
	DeadletterReasonRemoteReplyTimeout    DeadletterReason = 11
	DeadletterReasonLocalityMismatch      DeadletterReason = 12
	DeadletterReasonExpiredBeforeDelivery DeadletterReason = 13
	DeadletterReasonOneWayDroppedByPolicy DeadletterReason = 14
)

func (r DeadletterReason) String() string {
	switch r {
	case DeadletterReasonUnspecified:
		return "UNSPECIFIED"
	case DeadletterReasonNoActiveSnapshot:
		return "NO_ACTIVE_SNAPSHOT"
	case DeadletterReasonRouteMiss:
		return "ROUTE_MISS"
	case DeadletterReasonNoResponsibleHost:
		return "NO_RESPONSIBLE_HOST"
	case DeadletterReasonQueueRejected:
		return "QUEUE_REJECTED"
	case DeadletterReasonLocalHandoffFailed:
		return "LOCAL_HANDOFF_FAILED"
	case DeadletterReasonDeliveryFailed:
		return "DELIVERY_FAILED"
	case DeadletterReasonTransportSendFailed:
		return "TRANSPORT_SEND_FAILED"
	case DeadletterReasonRuntimeStopped:
		return "RUNTIME_STOPPED"
	case DeadletterReasonInvalidEnvelope:
		return "INVALID_ENVELOPE"
	case DeadletterReasonEndpointUnavailable:
		return "ENDPOINT_UNAVAILABLE"
	case DeadletterReasonRemoteReplyTimeout:
		return "REMOTE_REPLY_TIMEOUT"
	case DeadletterReasonLocalityMismatch:
		return "LOCALITY_MISMATCH"
	case DeadletterReasonExpiredBeforeDelivery:
		return "EXPIRED_BEFORE_DELIVERY"
	case DeadletterReasonOneWayDroppedByPolicy:
		return "ONE_WAY_DROPPED_BY_POLICY"
	default:
		return fmt.Sprintf("UNKNOWN(%d)", r)
	}
}

// Envelope is the connector-owned message contract exchanged with handlers and
// request APIs. Payload and Headers remain owned by the caller until a submit
// method returns; the connector snapshots them before asynchronous tracking.
// Received envelopes own their Payload and Headers and may be retained by the
// application after the callback returns.
//
// The Id and Ms spellings are retained for source compatibility with earlier
// Go connector releases. Prefer the constructors and Get methods when possible.
type Envelope struct {
	MessageId     string      `json:"message_id,omitempty"`     // Unique message identity supplied or generated by the sender.
	CorrelationId string      `json:"correlation_id,omitempty"` // Request identity shared by its response or terminal deadletter.
	Source        string      `json:"source,omitempty"`         // Logical sender name.
	Target        string      `json:"target,omitempty"`         // Logical route target, not a network address.
	ReplyTo       string      `json:"reply_to,omitempty"`       // Logical reply target; empty for one-way messages.
	Kind          MessageKind `json:"kind,omitempty"`           // Request, response, or event classification.
	OneWay        bool        `json:"one_way,omitempty"`        // True when no response is expected.
	TimeoutMs     int32       `json:"timeout_ms,omitempty"`     // End-to-end delivery budget in milliseconds; zero means unspecified.
	Payload       []byte      `json:"payload,omitempty"`        // Opaque application bytes described by the payload identity fields.

	// Headers carry application metadata. They do not configure connector routing,
	// connection strategy, or transport security.
	Headers map[string]string `json:"headers,omitempty"`

	Status       BusinessStatus `json:"status,omitempty"`        // Application result status, primarily used by responses.
	ErrorCode    string         `json:"error_code,omitempty"`    // Stable application error code when Status is error.
	ErrorMessage string         `json:"error_message,omitempty"` // Human-readable application error detail.
	DeliveryHint DeliveryHint   `json:"delivery_hint,omitempty"` // Routing constraint interpreted by the core runtime.

	MessageType          string        `json:"message_type,omitempty"`           // Stable application schema name.
	PayloadSchemaVersion uint32        `json:"payload_schema_version,omitempty"` // Application schema version; typed APIs require at least one.
	PayloadFormat        PayloadFormat `json:"payload_format,omitempty"`         // Encoding of Payload supplied by the application.
}

func (e *Envelope) GetMessageId() string {
	if e == nil {
		return ""
	}
	return e.MessageId
}

func (e *Envelope) GetCorrelationId() string {
	if e == nil {
		return ""
	}
	return e.CorrelationId
}

func (e *Envelope) GetSource() string {
	if e == nil {
		return ""
	}
	return e.Source
}

func (e *Envelope) GetTarget() string {
	if e == nil {
		return ""
	}
	return e.Target
}

func (e *Envelope) GetReplyTo() string {
	if e == nil {
		return ""
	}
	return e.ReplyTo
}

func (e *Envelope) GetKind() MessageKind {
	if e == nil {
		return MessageKindUnspecified
	}
	return e.Kind
}

func (e *Envelope) GetOneWay() bool {
	return e != nil && e.OneWay
}

func (e *Envelope) GetTimeoutMs() int32 {
	if e == nil {
		return 0
	}
	return e.TimeoutMs
}

func (e *Envelope) GetPayload() []byte {
	if e == nil {
		return nil
	}
	return e.Payload
}

func (e *Envelope) GetHeaders() map[string]string {
	if e == nil {
		return nil
	}
	return e.Headers
}

func (e *Envelope) GetStatus() BusinessStatus {
	if e == nil {
		return BusinessStatusUnspecified
	}
	return e.Status
}

func (e *Envelope) GetErrorCode() string {
	if e == nil {
		return ""
	}
	return e.ErrorCode
}

func (e *Envelope) GetErrorMessage() string {
	if e == nil {
		return ""
	}
	return e.ErrorMessage
}

func (e *Envelope) GetDeliveryHint() DeliveryHint {
	if e == nil {
		return DeliveryHintUnspecified
	}
	return e.DeliveryHint
}

func (e *Envelope) GetMessageType() string {
	if e == nil {
		return ""
	}
	return e.MessageType
}

func (e *Envelope) GetPayloadSchemaVersion() uint32 {
	if e == nil {
		return 0
	}
	return e.PayloadSchemaVersion
}

func (e *Envelope) GetPayloadFormat() PayloadFormat {
	if e == nil {
		return PayloadFormatUnspecified
	}
	return e.PayloadFormat
}

// Deadletter describes a terminal delivery failure. OriginalEnvelope is a
// connector-owned snapshot of the submitted message and may be nil only when a
// malformed runtime frame could not supply one.
type Deadletter struct {
	OriginalEnvelope *Envelope        `json:"original_envelope,omitempty"` // Immutable delivery-attempt snapshot.
	Reason           DeadletterReason `json:"reason,omitempty"`            // Stable machine-readable terminal reason.
	Detail           string           `json:"detail,omitempty"`            // Human-readable diagnostic detail; do not branch on it.
	ActiveGeneration uint64           `json:"active_generation,omitempty"` // Route generation active when delivery terminated.
	ResolvedHost     string           `json:"resolved_host,omitempty"`     // Selected host when resolution progressed that far.
	ResolvedPort     uint32           `json:"resolved_port,omitempty"`     // Selected port when resolution progressed that far.
}

func (d *Deadletter) GetOriginalEnvelope() *Envelope {
	if d == nil {
		return nil
	}
	return d.OriginalEnvelope
}

func (d *Deadletter) GetReason() DeadletterReason {
	if d == nil {
		return DeadletterReasonUnspecified
	}
	return d.Reason
}

func (d *Deadletter) GetDetail() string {
	if d == nil {
		return ""
	}
	return d.Detail
}

func (d *Deadletter) GetActiveGeneration() uint64 {
	if d == nil {
		return 0
	}
	return d.ActiveGeneration
}

func (d *Deadletter) GetResolvedHost() string {
	if d == nil {
		return ""
	}
	return d.ResolvedHost
}

func (d *Deadletter) GetResolvedPort() uint32 {
	if d == nil {
		return 0
	}
	return d.ResolvedPort
}

type RouteStrategy int32

const (
	RouteStrategyUnspecified        RouteStrategy = 0
	RouteStrategySingleOwner        RouteStrategy = 1
	RouteStrategyWeightedRoundRobin RouteStrategy = 2
	RouteStrategyRendezvousHash     RouteStrategy = 3
)

type OverloadMode int32

const (
	OverloadModeReject           OverloadMode = 0
	OverloadModeDropExpiredFirst OverloadMode = 1
	OverloadModeDropOneWayFirst  OverloadMode = 2
)

type EndpointFlag uint32

const (
	EndpointFlagNone        EndpointFlag = 0
	EndpointFlagLocal       EndpointFlag = 1
	EndpointFlagUnavailable EndpointFlag = 1 << 1
)

type PayloadIdentity struct {
	MessageType          string
	PayloadSchemaVersion uint32
	PayloadFormat        PayloadFormat
}

func NewPayloadIdentity(messageType string, payloadSchemaVersion uint32, payloadFormat PayloadFormat) PayloadIdentity {
	return PayloadIdentity{
		MessageType:          messageType,
		PayloadSchemaVersion: payloadSchemaVersion,
		PayloadFormat:        payloadFormat,
	}
}

func NewTextPayloadIdentity(messageType string) PayloadIdentity {
	return NewPayloadIdentity(messageType, 1, PayloadFormatText)
}

func (p PayloadIdentity) IsTyped() bool {
	return strings.TrimSpace(p.MessageType) != "" &&
		p.PayloadSchemaVersion >= 1 &&
		p.PayloadFormat != PayloadFormatUnspecified
}

func (p PayloadIdentity) RequireTyped(what string) error {
	if strings.TrimSpace(p.MessageType) == "" {
		return fmt.Errorf("%s requires messageType", what)
	}
	if p.PayloadSchemaVersion < 1 {
		return fmt.Errorf("%s requires payloadSchemaVersion >= 1", what)
	}
	if p.PayloadFormat == PayloadFormatUnspecified {
		return fmt.Errorf("%s requires declared payloadFormat", what)
	}
	return nil
}

type EndpointSpec struct {
	Host   string
	Port   uint32
	Weight uint32
	Flags  uint32
}

type RouteSpec struct {
	Target       string
	Endpoints    []EndpointSpec
	Strategy     RouteStrategy
	RouteKeyHint string
	Flags        uint32
}

func LocalRoute(target string, port uint32) RouteSpec {
	return RouteSpec{
		Target: target,
		Endpoints: []EndpointSpec{{
			Host:   "127.0.0.1",
			Port:   port,
			Weight: 1,
			Flags:  uint32(EndpointFlagLocal),
		}},
		Strategy: RouteStrategySingleOwner,
	}
}

func LocalRouteDefault(target string) RouteSpec {
	return LocalRoute(target, 9001)
}

func (r RouteSpec) RequireValid() error {
	if strings.TrimSpace(r.Target) == "" {
		return fmt.Errorf("route requires target")
	}
	if len(r.Endpoints) == 0 {
		return fmt.Errorf("route target=%s requires at least one endpoint", r.Target)
	}
	return nil
}

type RuntimeOverloadPolicy struct {
	IngressMode                     OverloadMode
	LocalDeliveryMode               OverloadMode
	RemoteOutboundMode              OverloadMode
	RemoteOutboundReplyReserveSlots uint32
}

func (p RuntimeOverloadPolicy) RequireValid() error {
	if p.IngressMode != OverloadModeReject {
		return fmt.Errorf("overload policy ingress mode currently supports only reject")
	}
	if p.LocalDeliveryMode != OverloadModeReject {
		return fmt.Errorf("overload policy local delivery mode currently supports only reject")
	}
	return nil
}

type ConnectorConfig struct {
	SystemName                   string
	NodeID                       string
	Routes                       []RouteSpec
	StrictNoDrop                 bool
	QueueCapacity                int
	EnableMonitor                bool
	SeparateDeliveredRequestLane bool
	Generation                   uint64
	OverloadPolicy               *RuntimeOverloadPolicy
	ConnectionStrategy           *RuntimeTCPConnectionStrategySpec
	Security                     *RuntimeTCPSecuritySpec
}

func (c ConnectorConfig) RequireValid() error {
	if strings.TrimSpace(c.SystemName) == "" {
		return fmt.Errorf("connector config requires systemName")
	}
	if strings.TrimSpace(c.NodeID) == "" {
		return fmt.Errorf("connector config requires nodeId")
	}
	if c.QueueCapacity < 1 {
		return fmt.Errorf("connector config requires queueCapacity >= 1")
	}
	if c.Generation < 1 {
		return fmt.Errorf("connector config requires generation >= 1")
	}
	if c.OverloadPolicy != nil {
		if err := c.OverloadPolicy.RequireValid(); err != nil {
			return err
		}
	}
	if len(c.Routes) == 0 {
		return fmt.Errorf("connector config requires at least one route")
	}
	for _, route := range c.Routes {
		if err := route.RequireValid(); err != nil {
			return err
		}
	}
	return nil
}

type ConnectorStartSpec struct {
	SystemName                          string
	NodeID                              string
	Routes                              []RouteSpec
	StrictNoDrop                        bool
	QueueCapacity                       int
	EnableMonitor                       bool
	SeparateDeliveredRequestLane        bool
	DisableSeparateDeliveredRequestLane bool
	Generation                          uint64
	OverloadPolicy                      *RuntimeOverloadPolicy
	ConnectionStrategy                  *RuntimeTCPConnectionStrategySpec
	Security                            *RuntimeTCPSecuritySpec
}

func (s ConnectorStartSpec) ToConnectorConfig() ConnectorConfig {
	normalized := s.Normalized()
	return ConnectorConfig{
		SystemName:                   normalized.SystemName,
		NodeID:                       normalized.NodeID,
		Routes:                       normalized.Routes,
		StrictNoDrop:                 normalized.StrictNoDrop,
		QueueCapacity:                normalized.QueueCapacity,
		EnableMonitor:                normalized.EnableMonitor,
		SeparateDeliveredRequestLane: normalized.SeparateDeliveredRequestLane,
		Generation:                   normalized.Generation,
		OverloadPolicy:               normalized.OverloadPolicy,
		ConnectionStrategy:           normalized.ConnectionStrategy,
		Security:                     normalized.Security,
	}
}

func (s ConnectorStartSpec) Normalized() ConnectorStartSpec {
	out := s
	if out.QueueCapacity == 0 {
		out.QueueCapacity = 128
	}
	if out.Generation == 0 {
		out.Generation = 1
	}
	if !out.EnableMonitor {
		out.EnableMonitor = true
	}
	if !out.DisableSeparateDeliveredRequestLane {
		out.SeparateDeliveredRequestLane = true
	}
	if !out.StrictNoDrop {
		out.StrictNoDrop = true
	}
	return out
}

func (s ConnectorStartSpec) RequireValid() error {
	return s.ToConnectorConfig().RequireValid()
}

type SubmittedRequest struct {
	MessageID     string
	CorrelationID string
}

type RequestTerminalEventKind string

const (
	RequestTerminalEventResponse   RequestTerminalEventKind = "response"
	RequestTerminalEventDeadletter RequestTerminalEventKind = "deadletter"
)

type RequestTerminalEvent struct {
	Kind             RequestTerminalEventKind
	RequestMessageID string
	CorrelationID    string
	Response         *Envelope
	Deadletter       *Deadletter
}

type ObservedDeadletter struct {
	Deadletter            *Deadletter `json:"deadletter"`
	RequestMessageID      string      `json:"requestMessageId,omitempty"`
	CorrelationID         string      `json:"correlationId,omitempty"`
	MatchedPendingRequest bool        `json:"matchedPendingRequest"`
}
