// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: coakka/v2/control.proto

package coakkav2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlKind int32

const (
	ControlKind_CONTROL_KIND_UNSPECIFIED    ControlKind = 0
	ControlKind_CONTROL_KIND_APPLY_SNAPSHOT ControlKind = 1
	ControlKind_CONTROL_KIND_ACK            ControlKind = 2
	ControlKind_CONTROL_KIND_NACK           ControlKind = 3
)

// Enum value maps for ControlKind.
var (
	ControlKind_name = map[int32]string{
		0: "CONTROL_KIND_UNSPECIFIED",
		1: "CONTROL_KIND_APPLY_SNAPSHOT",
		2: "CONTROL_KIND_ACK",
		3: "CONTROL_KIND_NACK",
	}
	ControlKind_value = map[string]int32{
		"CONTROL_KIND_UNSPECIFIED":    0,
		"CONTROL_KIND_APPLY_SNAPSHOT": 1,
		"CONTROL_KIND_ACK":            2,
		"CONTROL_KIND_NACK":           3,
	}
)

func (x ControlKind) Enum() *ControlKind {
	p := new(ControlKind)
	*p = x
	return p
}

func (x ControlKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlKind) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_control_proto_enumTypes[0].Descriptor()
}

func (ControlKind) Type() protoreflect.EnumType {
	return &file_coakka_v2_control_proto_enumTypes[0]
}

func (x ControlKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlKind.Descriptor instead.
func (ControlKind) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{0}
}

type ConfigFormat int32

const (
	ConfigFormat_CONFIG_FORMAT_UNSPECIFIED ConfigFormat = 0
	ConfigFormat_CONFIG_FORMAT_JSON        ConfigFormat = 1
	ConfigFormat_CONFIG_FORMAT_PROTOBUF    ConfigFormat = 2
)

// Enum value maps for ConfigFormat.
var (
	ConfigFormat_name = map[int32]string{
		0: "CONFIG_FORMAT_UNSPECIFIED",
		1: "CONFIG_FORMAT_JSON",
		2: "CONFIG_FORMAT_PROTOBUF",
	}
	ConfigFormat_value = map[string]int32{
		"CONFIG_FORMAT_UNSPECIFIED": 0,
		"CONFIG_FORMAT_JSON":        1,
		"CONFIG_FORMAT_PROTOBUF":    2,
	}
)

func (x ConfigFormat) Enum() *ConfigFormat {
	p := new(ConfigFormat)
	*p = x
	return p
}

func (x ConfigFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_control_proto_enumTypes[1].Descriptor()
}

func (ConfigFormat) Type() protoreflect.EnumType {
	return &file_coakka_v2_control_proto_enumTypes[1]
}

func (x ConfigFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigFormat.Descriptor instead.
func (ConfigFormat) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{1}
}

type ControlPayloadType int32

const (
	ControlPayloadType_CONTROL_PAYLOAD_TYPE_UNSPECIFIED    ControlPayloadType = 0
	ControlPayloadType_CONTROL_PAYLOAD_TYPE_ROUTE_SNAPSHOT ControlPayloadType = 1
)

// Enum value maps for ControlPayloadType.
var (
	ControlPayloadType_name = map[int32]string{
		0: "CONTROL_PAYLOAD_TYPE_UNSPECIFIED",
		1: "CONTROL_PAYLOAD_TYPE_ROUTE_SNAPSHOT",
	}
	ControlPayloadType_value = map[string]int32{
		"CONTROL_PAYLOAD_TYPE_UNSPECIFIED":    0,
		"CONTROL_PAYLOAD_TYPE_ROUTE_SNAPSHOT": 1,
	}
)

func (x ControlPayloadType) Enum() *ControlPayloadType {
	p := new(ControlPayloadType)
	*p = x
	return p
}

func (x ControlPayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlPayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_control_proto_enumTypes[2].Descriptor()
}

func (ControlPayloadType) Type() protoreflect.EnumType {
	return &file_coakka_v2_control_proto_enumTypes[2]
}

func (x ControlPayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlPayloadType.Descriptor instead.
func (ControlPayloadType) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{2}
}

type RouteResolutionStrategy int32

const (
	RouteResolutionStrategy_ROUTE_RESOLUTION_STRATEGY_UNSPECIFIED          RouteResolutionStrategy = 0
	RouteResolutionStrategy_ROUTE_RESOLUTION_STRATEGY_SINGLE_OWNER         RouteResolutionStrategy = 1
	RouteResolutionStrategy_ROUTE_RESOLUTION_STRATEGY_WEIGHTED_ROUND_ROBIN RouteResolutionStrategy = 2
	RouteResolutionStrategy_ROUTE_RESOLUTION_STRATEGY_RENDEZVOUS_HASH      RouteResolutionStrategy = 3
)

// Enum value maps for RouteResolutionStrategy.
var (
	RouteResolutionStrategy_name = map[int32]string{
		0: "ROUTE_RESOLUTION_STRATEGY_UNSPECIFIED",
		1: "ROUTE_RESOLUTION_STRATEGY_SINGLE_OWNER",
		2: "ROUTE_RESOLUTION_STRATEGY_WEIGHTED_ROUND_ROBIN",
		3: "ROUTE_RESOLUTION_STRATEGY_RENDEZVOUS_HASH",
	}
	RouteResolutionStrategy_value = map[string]int32{
		"ROUTE_RESOLUTION_STRATEGY_UNSPECIFIED":          0,
		"ROUTE_RESOLUTION_STRATEGY_SINGLE_OWNER":         1,
		"ROUTE_RESOLUTION_STRATEGY_WEIGHTED_ROUND_ROBIN": 2,
		"ROUTE_RESOLUTION_STRATEGY_RENDEZVOUS_HASH":      3,
	}
)

func (x RouteResolutionStrategy) Enum() *RouteResolutionStrategy {
	p := new(RouteResolutionStrategy)
	*p = x
	return p
}

func (x RouteResolutionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteResolutionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_control_proto_enumTypes[3].Descriptor()
}

func (RouteResolutionStrategy) Type() protoreflect.EnumType {
	return &file_coakka_v2_control_proto_enumTypes[3]
}

func (x RouteResolutionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteResolutionStrategy.Descriptor instead.
func (RouteResolutionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{3}
}

type OverloadMode int32

const (
	OverloadMode_OVERLOAD_MODE_REJECT             OverloadMode = 0
	OverloadMode_OVERLOAD_MODE_DROP_EXPIRED_FIRST OverloadMode = 1
	OverloadMode_OVERLOAD_MODE_DROP_ONE_WAY_FIRST OverloadMode = 2
)

// Enum value maps for OverloadMode.
var (
	OverloadMode_name = map[int32]string{
		0: "OVERLOAD_MODE_REJECT",
		1: "OVERLOAD_MODE_DROP_EXPIRED_FIRST",
		2: "OVERLOAD_MODE_DROP_ONE_WAY_FIRST",
	}
	OverloadMode_value = map[string]int32{
		"OVERLOAD_MODE_REJECT":             0,
		"OVERLOAD_MODE_DROP_EXPIRED_FIRST": 1,
		"OVERLOAD_MODE_DROP_ONE_WAY_FIRST": 2,
	}
)

func (x OverloadMode) Enum() *OverloadMode {
	p := new(OverloadMode)
	*p = x
	return p
}

func (x OverloadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverloadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_control_proto_enumTypes[4].Descriptor()
}

func (OverloadMode) Type() protoreflect.EnumType {
	return &file_coakka_v2_control_proto_enumTypes[4]
}

func (x OverloadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverloadMode.Descriptor instead.
func (OverloadMode) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{4}
}

type ControlEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Kind          ControlKind            `protobuf:"varint,3,opt,name=kind,proto3,enum=coakka.v2.control.ControlKind" json:"kind,omitempty"`
	PayloadFormat ConfigFormat           `protobuf:"varint,4,opt,name=payload_format,json=payloadFormat,proto3,enum=coakka.v2.control.ConfigFormat" json:"payload_format,omitempty"`
	PayloadType   ControlPayloadType     `protobuf:"varint,5,opt,name=payload_type,json=payloadType,proto3,enum=coakka.v2.control.ControlPayloadType" json:"payload_type,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEnvelope) Reset() {
	*x = ControlEnvelope{}
	mi := &file_coakka_v2_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEnvelope) ProtoMessage() {}

func (x *ControlEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_coakka_v2_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEnvelope.ProtoReflect.Descriptor instead.
func (*ControlEnvelope) Descriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ControlEnvelope) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ControlEnvelope) GetKind() ControlKind {
	if x != nil {
		return x.Kind
	}
	return ControlKind_CONTROL_KIND_UNSPECIFIED
}

func (x *ControlEnvelope) GetPayloadFormat() ConfigFormat {
	if x != nil {
		return x.PayloadFormat
	}
	return ConfigFormat_CONFIG_FORMAT_UNSPECIFIED
}

func (x *ControlEnvelope) GetPayloadType() ControlPayloadType {
	if x != nil {
		return x.PayloadType
	}
	return ControlPayloadType_CONTROL_PAYLOAD_TYPE_UNSPECIFIED
}

func (x *ControlEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ControlEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RouteSnapshotPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Generation     uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Routes         []*Route               `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	OverloadPolicy *OverloadPolicy        `protobuf:"bytes,3,opt,name=overload_policy,json=overloadPolicy,proto3" json:"overload_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteSnapshotPayload) Reset() {
	*x = RouteSnapshotPayload{}
	mi := &file_coakka_v2_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSnapshotPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSnapshotPayload) ProtoMessage() {}

func (x *RouteSnapshotPayload) ProtoReflect() protoreflect.Message {
	mi := &file_coakka_v2_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSnapshotPayload.ProtoReflect.Descriptor instead.
func (*RouteSnapshotPayload) Descriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{1}
}

func (x *RouteSnapshotPayload) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RouteSnapshotPayload) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteSnapshotPayload) GetOverloadPolicy() *OverloadPolicy {
	if x != nil {
		return x.OverloadPolicy
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Target        string                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Strategy      RouteResolutionStrategy `protobuf:"varint,2,opt,name=strategy,proto3,enum=coakka.v2.control.RouteResolutionStrategy" json:"strategy,omitempty"`
	RouteKeyHint  string                  `protobuf:"bytes,3,opt,name=route_key_hint,json=routeKeyHint,proto3" json:"route_key_hint,omitempty"`
	Flags         uint32                  `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	Endpoints     []*Endpoint             `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_coakka_v2_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_coakka_v2_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Route) GetStrategy() RouteResolutionStrategy {
	if x != nil {
		return x.Strategy
	}
	return RouteResolutionStrategy_ROUTE_RESOLUTION_STRATEGY_UNSPECIFIED
}

func (x *Route) GetRouteKeyHint() string {
	if x != nil {
		return x.RouteKeyHint
	}
	return ""
}

func (x *Route) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Route) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Weight        uint32                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_coakka_v2_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_coakka_v2_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{3}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Endpoint) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Endpoint) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type OverloadPolicy struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	IngressMode                     OverloadMode           `protobuf:"varint,1,opt,name=ingress_mode,json=ingressMode,proto3,enum=coakka.v2.control.OverloadMode" json:"ingress_mode,omitempty"`
	LocalDeliveryMode               OverloadMode           `protobuf:"varint,2,opt,name=local_delivery_mode,json=localDeliveryMode,proto3,enum=coakka.v2.control.OverloadMode" json:"local_delivery_mode,omitempty"`
	RemoteOutboundMode              OverloadMode           `protobuf:"varint,3,opt,name=remote_outbound_mode,json=remoteOutboundMode,proto3,enum=coakka.v2.control.OverloadMode" json:"remote_outbound_mode,omitempty"`
	RemoteOutboundReplyReserveSlots uint32                 `protobuf:"varint,4,opt,name=remote_outbound_reply_reserve_slots,json=remoteOutboundReplyReserveSlots,proto3" json:"remote_outbound_reply_reserve_slots,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *OverloadPolicy) Reset() {
	*x = OverloadPolicy{}
	mi := &file_coakka_v2_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverloadPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverloadPolicy) ProtoMessage() {}

func (x *OverloadPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_coakka_v2_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverloadPolicy.ProtoReflect.Descriptor instead.
func (*OverloadPolicy) Descriptor() ([]byte, []int) {
	return file_coakka_v2_control_proto_rawDescGZIP(), []int{4}
}

func (x *OverloadPolicy) GetIngressMode() OverloadMode {
	if x != nil {
		return x.IngressMode
	}
	return OverloadMode_OVERLOAD_MODE_REJECT
}

func (x *OverloadPolicy) GetLocalDeliveryMode() OverloadMode {
	if x != nil {
		return x.LocalDeliveryMode
	}
	return OverloadMode_OVERLOAD_MODE_REJECT
}

func (x *OverloadPolicy) GetRemoteOutboundMode() OverloadMode {
	if x != nil {
		return x.RemoteOutboundMode
	}
	return OverloadMode_OVERLOAD_MODE_REJECT
}

func (x *OverloadPolicy) GetRemoteOutboundReplyReserveSlots() uint32 {
	if x != nil {
		return x.RemoteOutboundReplyReserveSlots
	}
	return 0
}

var File_coakka_v2_control_proto protoreflect.FileDescriptor

const file_coakka_v2_control_proto_rawDesc = "" +
	"\n" +
	"\x17coakka/v2/control.proto\x12\x11coakka.v2.control\"\xd5\x03\n" +
	"\x0fControlEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x122\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1e.coakka.v2.control.ControlKindR\x04kind\x12F\n" +
	"\x0epayload_format\x18\x04 \x01(\x0e2\x1f.coakka.v2.control.ConfigFormatR\rpayloadFormat\x12H\n" +
	"\fpayload_type\x18\x05 \x01(\x0e2%.coakka.v2.control.ControlPayloadTypeR\vpayloadType\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\rR\rschemaVersion\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12L\n" +
	"\bmetadata\x18\b \x03(\v20.coakka.v2.control.ControlEnvelope.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x14RouteSnapshotPayload\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x120\n" +
	"\x06routes\x18\x02 \x03(\v2\x18.coakka.v2.control.RouteR\x06routes\x12J\n" +
	"\x0foverload_policy\x18\x03 \x01(\v2!.coakka.v2.control.OverloadPolicyR\x0eoverloadPolicy\"\xde\x01\n" +
	"\x05Route\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12F\n" +
	"\bstrategy\x18\x02 \x01(\x0e2*.coakka.v2.control.RouteResolutionStrategyR\bstrategy\x12$\n" +
	"\x0eroute_key_hint\x18\x03 \x01(\tR\frouteKeyHint\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x129\n" +
	"\tendpoints\x18\x05 \x03(\v2\x1b.coakka.v2.control.EndpointR\tendpoints\"`\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\"\xc6\x02\n" +
	"\x0eOverloadPolicy\x12B\n" +
	"\fingress_mode\x18\x01 \x01(\x0e2\x1f.coakka.v2.control.OverloadModeR\vingressMode\x12O\n" +
	"\x13local_delivery_mode\x18\x02 \x01(\x0e2\x1f.coakka.v2.control.OverloadModeR\x11localDeliveryMode\x12Q\n" +
	"\x14remote_outbound_mode\x18\x03 \x01(\x0e2\x1f.coakka.v2.control.OverloadModeR\x12remoteOutboundMode\x12L\n" +
	"#remote_outbound_reply_reserve_slots\x18\x04 \x01(\rR\x1fremoteOutboundReplyReserveSlots*y\n" +
	"\vControlKind\x12\x1c\n" +
	"\x18CONTROL_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCONTROL_KIND_APPLY_SNAPSHOT\x10\x01\x12\x14\n" +
	"\x10CONTROL_KIND_ACK\x10\x02\x12\x15\n" +
	"\x11CONTROL_KIND_NACK\x10\x03*a\n" +
	"\fConfigFormat\x12\x1d\n" +
	"\x19CONFIG_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONFIG_FORMAT_JSON\x10\x01\x12\x1a\n" +
	"\x16CONFIG_FORMAT_PROTOBUF\x10\x02*c\n" +
	"\x12ControlPayloadType\x12$\n" +
	" CONTROL_PAYLOAD_TYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#CONTROL_PAYLOAD_TYPE_ROUTE_SNAPSHOT\x10\x01*\xd3\x01\n" +
	"\x17RouteResolutionStrategy\x12)\n" +
	"%ROUTE_RESOLUTION_STRATEGY_UNSPECIFIED\x10\x00\x12*\n" +
	"&ROUTE_RESOLUTION_STRATEGY_SINGLE_OWNER\x10\x01\x122\n" +
	".ROUTE_RESOLUTION_STRATEGY_WEIGHTED_ROUND_ROBIN\x10\x02\x12-\n" +
	")ROUTE_RESOLUTION_STRATEGY_RENDEZVOUS_HASH\x10\x03*t\n" +
	"\fOverloadMode\x12\x18\n" +
	"\x14OVERLOAD_MODE_REJECT\x10\x00\x12$\n" +
	" OVERLOAD_MODE_DROP_EXPIRED_FIRST\x10\x01\x12$\n" +
	" OVERLOAD_MODE_DROP_ONE_WAY_FIRST\x10\x02BR\n" +
	"\x11coakka.v2.controlP\x01Z;github.com/phuong-tran/coakka-runtime-go/coakka/v2;coakkav2b\x06proto3"

var (
	file_coakka_v2_control_proto_rawDescOnce sync.Once
	file_coakka_v2_control_proto_rawDescData []byte
)

func file_coakka_v2_control_proto_rawDescGZIP() []byte {
	file_coakka_v2_control_proto_rawDescOnce.Do(func() {
		file_coakka_v2_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coakka_v2_control_proto_rawDesc), len(file_coakka_v2_control_proto_rawDesc)))
	})
	return file_coakka_v2_control_proto_rawDescData
}

var file_coakka_v2_control_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_coakka_v2_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_coakka_v2_control_proto_goTypes = []any{
	(ControlKind)(0),             // 0: coakka.v2.control.ControlKind
	(ConfigFormat)(0),            // 1: coakka.v2.control.ConfigFormat
	(ControlPayloadType)(0),      // 2: coakka.v2.control.ControlPayloadType
	(RouteResolutionStrategy)(0), // 3: coakka.v2.control.RouteResolutionStrategy
	(OverloadMode)(0),            // 4: coakka.v2.control.OverloadMode
	(*ControlEnvelope)(nil),      // 5: coakka.v2.control.ControlEnvelope
	(*RouteSnapshotPayload)(nil), // 6: coakka.v2.control.RouteSnapshotPayload
	(*Route)(nil),                // 7: coakka.v2.control.Route
	(*Endpoint)(nil),             // 8: coakka.v2.control.Endpoint
	(*OverloadPolicy)(nil),       // 9: coakka.v2.control.OverloadPolicy
	nil,                          // 10: coakka.v2.control.ControlEnvelope.MetadataEntry
}
var file_coakka_v2_control_proto_depIdxs = []int32{
	0,  // 0: coakka.v2.control.ControlEnvelope.kind:type_name -> coakka.v2.control.ControlKind
	1,  // 1: coakka.v2.control.ControlEnvelope.payload_format:type_name -> coakka.v2.control.ConfigFormat
	2,  // 2: coakka.v2.control.ControlEnvelope.payload_type:type_name -> coakka.v2.control.ControlPayloadType
	10, // 3: coakka.v2.control.ControlEnvelope.metadata:type_name -> coakka.v2.control.ControlEnvelope.MetadataEntry
	7,  // 4: coakka.v2.control.RouteSnapshotPayload.routes:type_name -> coakka.v2.control.Route
	9,  // 5: coakka.v2.control.RouteSnapshotPayload.overload_policy:type_name -> coakka.v2.control.OverloadPolicy
	3,  // 6: coakka.v2.control.Route.strategy:type_name -> coakka.v2.control.RouteResolutionStrategy
	8,  // 7: coakka.v2.control.Route.endpoints:type_name -> coakka.v2.control.Endpoint
	4,  // 8: coakka.v2.control.OverloadPolicy.ingress_mode:type_name -> coakka.v2.control.OverloadMode
	4,  // 9: coakka.v2.control.OverloadPolicy.local_delivery_mode:type_name -> coakka.v2.control.OverloadMode
	4,  // 10: coakka.v2.control.OverloadPolicy.remote_outbound_mode:type_name -> coakka.v2.control.OverloadMode
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_coakka_v2_control_proto_init() }
func file_coakka_v2_control_proto_init() {
	if File_coakka_v2_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coakka_v2_control_proto_rawDesc), len(file_coakka_v2_control_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coakka_v2_control_proto_goTypes,
		DependencyIndexes: file_coakka_v2_control_proto_depIdxs,
		EnumInfos:         file_coakka_v2_control_proto_enumTypes,
		MessageInfos:      file_coakka_v2_control_proto_msgTypes,
	}.Build()
	File_coakka_v2_control_proto = out.File
	file_coakka_v2_control_proto_goTypes = nil
	file_coakka_v2_control_proto_depIdxs = nil
}
