// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: coakka/v2/transport.proto

package wirepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageKind int32

const (
	MessageKind_MESSAGE_KIND_UNSPECIFIED MessageKind = 0
	MessageKind_MESSAGE_KIND_REQUEST     MessageKind = 1
	MessageKind_MESSAGE_KIND_RESPONSE    MessageKind = 2
	MessageKind_MESSAGE_KIND_EVENT       MessageKind = 3
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0: "MESSAGE_KIND_UNSPECIFIED",
		1: "MESSAGE_KIND_REQUEST",
		2: "MESSAGE_KIND_RESPONSE",
		3: "MESSAGE_KIND_EVENT",
	}
	MessageKind_value = map[string]int32{
		"MESSAGE_KIND_UNSPECIFIED": 0,
		"MESSAGE_KIND_REQUEST":     1,
		"MESSAGE_KIND_RESPONSE":    2,
		"MESSAGE_KIND_EVENT":       3,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_transport_proto_enumTypes[0].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_coakka_v2_transport_proto_enumTypes[0]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_transport_proto_rawDescGZIP(), []int{0}
}

type BusinessStatus int32

const (
	BusinessStatus_BUSINESS_STATUS_UNSPECIFIED BusinessStatus = 0
	BusinessStatus_BUSINESS_STATUS_OK          BusinessStatus = 1
	BusinessStatus_BUSINESS_STATUS_ERROR       BusinessStatus = 2
)

// Enum value maps for BusinessStatus.
var (
	BusinessStatus_name = map[int32]string{
		0: "BUSINESS_STATUS_UNSPECIFIED",
		1: "BUSINESS_STATUS_OK",
		2: "BUSINESS_STATUS_ERROR",
	}
	BusinessStatus_value = map[string]int32{
		"BUSINESS_STATUS_UNSPECIFIED": 0,
		"BUSINESS_STATUS_OK":          1,
		"BUSINESS_STATUS_ERROR":       2,
	}
)

func (x BusinessStatus) Enum() *BusinessStatus {
	p := new(BusinessStatus)
	*p = x
	return p
}

func (x BusinessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusinessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_transport_proto_enumTypes[1].Descriptor()
}

func (BusinessStatus) Type() protoreflect.EnumType {
	return &file_coakka_v2_transport_proto_enumTypes[1]
}

func (x BusinessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusinessStatus.Descriptor instead.
func (BusinessStatus) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_transport_proto_rawDescGZIP(), []int{1}
}

type DeliveryHint int32

const (
	DeliveryHint_DELIVERY_HINT_UNSPECIFIED    DeliveryHint = 0
	DeliveryHint_DELIVERY_HINT_ROUTER_DEFAULT DeliveryHint = 1
	DeliveryHint_DELIVERY_HINT_PREFER_LOCAL   DeliveryHint = 2
	DeliveryHint_DELIVERY_HINT_REQUIRE_LOCAL  DeliveryHint = 3
	DeliveryHint_DELIVERY_HINT_REQUIRE_REMOTE DeliveryHint = 4
)

// Enum value maps for DeliveryHint.
var (
	DeliveryHint_name = map[int32]string{
		0: "DELIVERY_HINT_UNSPECIFIED",
		1: "DELIVERY_HINT_ROUTER_DEFAULT",
		2: "DELIVERY_HINT_PREFER_LOCAL",
		3: "DELIVERY_HINT_REQUIRE_LOCAL",
		4: "DELIVERY_HINT_REQUIRE_REMOTE",
	}
	DeliveryHint_value = map[string]int32{
		"DELIVERY_HINT_UNSPECIFIED":    0,
		"DELIVERY_HINT_ROUTER_DEFAULT": 1,
		"DELIVERY_HINT_PREFER_LOCAL":   2,
		"DELIVERY_HINT_REQUIRE_LOCAL":  3,
		"DELIVERY_HINT_REQUIRE_REMOTE": 4,
	}
)

func (x DeliveryHint) Enum() *DeliveryHint {
	p := new(DeliveryHint)
	*p = x
	return p
}

func (x DeliveryHint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryHint) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_transport_proto_enumTypes[2].Descriptor()
}

func (DeliveryHint) Type() protoreflect.EnumType {
	return &file_coakka_v2_transport_proto_enumTypes[2]
}

func (x DeliveryHint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryHint.Descriptor instead.
func (DeliveryHint) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_transport_proto_rawDescGZIP(), []int{2}
}

type PayloadFormat int32

const (
	PayloadFormat_PAYLOAD_FORMAT_UNSPECIFIED PayloadFormat = 0
	PayloadFormat_PAYLOAD_FORMAT_JSON        PayloadFormat = 1
	PayloadFormat_PAYLOAD_FORMAT_PROTOBUF    PayloadFormat = 2
	PayloadFormat_PAYLOAD_FORMAT_THRIFT      PayloadFormat = 3
	PayloadFormat_PAYLOAD_FORMAT_MSGPACK     PayloadFormat = 4
	PayloadFormat_PAYLOAD_FORMAT_PLAIN_TEXT  PayloadFormat = 5
	PayloadFormat_PAYLOAD_FORMAT_BINARY      PayloadFormat = 6
)

// Enum value maps for PayloadFormat.
var (
	PayloadFormat_name = map[int32]string{
		0: "PAYLOAD_FORMAT_UNSPECIFIED",
		1: "PAYLOAD_FORMAT_JSON",
		2: "PAYLOAD_FORMAT_PROTOBUF",
		3: "PAYLOAD_FORMAT_THRIFT",
		4: "PAYLOAD_FORMAT_MSGPACK",
		5: "PAYLOAD_FORMAT_PLAIN_TEXT",
		6: "PAYLOAD_FORMAT_BINARY",
	}
	PayloadFormat_value = map[string]int32{
		"PAYLOAD_FORMAT_UNSPECIFIED": 0,
		"PAYLOAD_FORMAT_JSON":        1,
		"PAYLOAD_FORMAT_PROTOBUF":    2,
		"PAYLOAD_FORMAT_THRIFT":      3,
		"PAYLOAD_FORMAT_MSGPACK":     4,
		"PAYLOAD_FORMAT_PLAIN_TEXT":  5,
		"PAYLOAD_FORMAT_BINARY":      6,
	}
)

func (x PayloadFormat) Enum() *PayloadFormat {
	p := new(PayloadFormat)
	*p = x
	return p
}

func (x PayloadFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_transport_proto_enumTypes[3].Descriptor()
}

func (PayloadFormat) Type() protoreflect.EnumType {
	return &file_coakka_v2_transport_proto_enumTypes[3]
}

func (x PayloadFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadFormat.Descriptor instead.
func (PayloadFormat) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_transport_proto_rawDescGZIP(), []int{3}
}

type DeadletterReason int32

const (
	DeadletterReason_DEADLETTER_REASON_UNSPECIFIED               DeadletterReason = 0
	DeadletterReason_DEADLETTER_REASON_NO_ACTIVE_SNAPSHOT        DeadletterReason = 1
	DeadletterReason_DEADLETTER_REASON_ROUTE_MISS                DeadletterReason = 2
	DeadletterReason_DEADLETTER_REASON_NO_RESPONSIBLE_HOST       DeadletterReason = 3
	DeadletterReason_DEADLETTER_REASON_QUEUE_REJECTED            DeadletterReason = 4
	DeadletterReason_DEADLETTER_REASON_LOCAL_HANDOFF_FAILED      DeadletterReason = 5
	DeadletterReason_DEADLETTER_REASON_DELIVERY_FAILED           DeadletterReason = 6
	DeadletterReason_DEADLETTER_REASON_CAF_SEND_FAILED           DeadletterReason = 7
	DeadletterReason_DEADLETTER_REASON_RUNTIME_STOPPED           DeadletterReason = 8
	DeadletterReason_DEADLETTER_REASON_INVALID_ENVELOPE          DeadletterReason = 9
	DeadletterReason_DEADLETTER_REASON_ENDPOINT_UNAVAILABLE      DeadletterReason = 10
	DeadletterReason_DEADLETTER_REASON_REMOTE_REPLY_TIMEOUT      DeadletterReason = 11
	DeadletterReason_DEADLETTER_REASON_LOCALITY_MISMATCH         DeadletterReason = 12
	DeadletterReason_DEADLETTER_REASON_EXPIRED_BEFORE_DELIVERY   DeadletterReason = 13
	DeadletterReason_DEADLETTER_REASON_ONE_WAY_DROPPED_BY_POLICY DeadletterReason = 14
)

// Enum value maps for DeadletterReason.
var (
	DeadletterReason_name = map[int32]string{
		0:  "DEADLETTER_REASON_UNSPECIFIED",
		1:  "DEADLETTER_REASON_NO_ACTIVE_SNAPSHOT",
		2:  "DEADLETTER_REASON_ROUTE_MISS",
		3:  "DEADLETTER_REASON_NO_RESPONSIBLE_HOST",
		4:  "DEADLETTER_REASON_QUEUE_REJECTED",
		5:  "DEADLETTER_REASON_LOCAL_HANDOFF_FAILED",
		6:  "DEADLETTER_REASON_DELIVERY_FAILED",
		7:  "DEADLETTER_REASON_CAF_SEND_FAILED",
		8:  "DEADLETTER_REASON_RUNTIME_STOPPED",
		9:  "DEADLETTER_REASON_INVALID_ENVELOPE",
		10: "DEADLETTER_REASON_ENDPOINT_UNAVAILABLE",
		11: "DEADLETTER_REASON_REMOTE_REPLY_TIMEOUT",
		12: "DEADLETTER_REASON_LOCALITY_MISMATCH",
		13: "DEADLETTER_REASON_EXPIRED_BEFORE_DELIVERY",
		14: "DEADLETTER_REASON_ONE_WAY_DROPPED_BY_POLICY",
	}
	DeadletterReason_value = map[string]int32{
		"DEADLETTER_REASON_UNSPECIFIED":               0,
		"DEADLETTER_REASON_NO_ACTIVE_SNAPSHOT":        1,
		"DEADLETTER_REASON_ROUTE_MISS":                2,
		"DEADLETTER_REASON_NO_RESPONSIBLE_HOST":       3,
		"DEADLETTER_REASON_QUEUE_REJECTED":            4,
		"DEADLETTER_REASON_LOCAL_HANDOFF_FAILED":      5,
		"DEADLETTER_REASON_DELIVERY_FAILED":           6,
		"DEADLETTER_REASON_CAF_SEND_FAILED":           7,
		"DEADLETTER_REASON_RUNTIME_STOPPED":           8,
		"DEADLETTER_REASON_INVALID_ENVELOPE":          9,
		"DEADLETTER_REASON_ENDPOINT_UNAVAILABLE":      10,
		"DEADLETTER_REASON_REMOTE_REPLY_TIMEOUT":      11,
		"DEADLETTER_REASON_LOCALITY_MISMATCH":         12,
		"DEADLETTER_REASON_EXPIRED_BEFORE_DELIVERY":   13,
		"DEADLETTER_REASON_ONE_WAY_DROPPED_BY_POLICY": 14,
	}
)

func (x DeadletterReason) Enum() *DeadletterReason {
	p := new(DeadletterReason)
	*p = x
	return p
}

func (x DeadletterReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeadletterReason) Descriptor() protoreflect.EnumDescriptor {
	return file_coakka_v2_transport_proto_enumTypes[4].Descriptor()
}

func (DeadletterReason) Type() protoreflect.EnumType {
	return &file_coakka_v2_transport_proto_enumTypes[4]
}

func (x DeadletterReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeadletterReason.Descriptor instead.
func (DeadletterReason) EnumDescriptor() ([]byte, []int) {
	return file_coakka_v2_transport_proto_rawDescGZIP(), []int{4}
}

type Envelope struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MessageId            string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CorrelationId        string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Source               string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Target               string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	ReplyTo              string                 `protobuf:"bytes,5,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Kind                 MessageKind            `protobuf:"varint,6,opt,name=kind,proto3,enum=coakka.v2.transport.MessageKind" json:"kind,omitempty"`
	OneWay               bool                   `protobuf:"varint,7,opt,name=one_way,json=oneWay,proto3" json:"one_way,omitempty"`
	TimeoutMs            int32                  `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Payload              []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers              map[string]string      `protobuf:"bytes,10,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status               BusinessStatus         `protobuf:"varint,11,opt,name=status,proto3,enum=coakka.v2.transport.BusinessStatus" json:"status,omitempty"`
	ErrorCode            string                 `protobuf:"bytes,12,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DeliveryHint         DeliveryHint           `protobuf:"varint,14,opt,name=delivery_hint,json=deliveryHint,proto3,enum=coakka.v2.transport.DeliveryHint" json:"delivery_hint,omitempty"`
	MessageType          string                 `protobuf:"bytes,15,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	PayloadSchemaVersion uint32                 `protobuf:"varint,16,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	PayloadFormat        PayloadFormat          `protobuf:"varint,17,opt,name=payload_format,json=payloadFormat,proto3,enum=coakka.v2.transport.PayloadFormat" json:"payload_format,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_coakka_v2_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_coakka_v2_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_coakka_v2_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Envelope) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Envelope) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *Envelope) GetKind() MessageKind {
	if x != nil {
		return x.Kind
	}
	return MessageKind_MESSAGE_KIND_UNSPECIFIED
}

func (x *Envelope) GetOneWay() bool {
	if x != nil {
		return x.OneWay
	}
	return false
}

func (x *Envelope) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Envelope) GetStatus() BusinessStatus {
	if x != nil {
		return x.Status
	}
	return BusinessStatus_BUSINESS_STATUS_UNSPECIFIED
}

func (x *Envelope) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Envelope) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Envelope) GetDeliveryHint() DeliveryHint {
	if x != nil {
		return x.DeliveryHint
	}
	return DeliveryHint_DELIVERY_HINT_UNSPECIFIED
}

func (x *Envelope) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Envelope) GetPayloadSchemaVersion() uint32 {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return 0
}

func (x *Envelope) GetPayloadFormat() PayloadFormat {
	if x != nil {
		return x.PayloadFormat
	}
	return PayloadFormat_PAYLOAD_FORMAT_UNSPECIFIED
}

type Deadletter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OriginalEnvelope *Envelope              `protobuf:"bytes,1,opt,name=original_envelope,json=originalEnvelope,proto3" json:"original_envelope,omitempty"`
	Reason           DeadletterReason       `protobuf:"varint,2,opt,name=reason,proto3,enum=coakka.v2.transport.DeadletterReason" json:"reason,omitempty"`
	Detail           string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	ActiveGeneration uint64                 `protobuf:"varint,4,opt,name=active_generation,json=activeGeneration,proto3" json:"active_generation,omitempty"`
	ResolvedHost     string                 `protobuf:"bytes,5,opt,name=resolved_host,json=resolvedHost,proto3" json:"resolved_host,omitempty"`
	ResolvedPort     uint32                 `protobuf:"varint,6,opt,name=resolved_port,json=resolvedPort,proto3" json:"resolved_port,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Deadletter) Reset() {
	*x = Deadletter{}
	mi := &file_coakka_v2_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deadletter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deadletter) ProtoMessage() {}

func (x *Deadletter) ProtoReflect() protoreflect.Message {
	mi := &file_coakka_v2_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deadletter.ProtoReflect.Descriptor instead.
func (*Deadletter) Descriptor() ([]byte, []int) {
	return file_coakka_v2_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Deadletter) GetOriginalEnvelope() *Envelope {
	if x != nil {
		return x.OriginalEnvelope
	}
	return nil
}

func (x *Deadletter) GetReason() DeadletterReason {
	if x != nil {
		return x.Reason
	}
	return DeadletterReason_DEADLETTER_REASON_UNSPECIFIED
}

func (x *Deadletter) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Deadletter) GetActiveGeneration() uint64 {
	if x != nil {
		return x.ActiveGeneration
	}
	return 0
}

func (x *Deadletter) GetResolvedHost() string {
	if x != nil {
		return x.ResolvedHost
	}
	return ""
}

func (x *Deadletter) GetResolvedPort() uint32 {
	if x != nil {
		return x.ResolvedPort
	}
	return 0
}

var File_coakka_v2_transport_proto protoreflect.FileDescriptor

const file_coakka_v2_transport_proto_rawDesc = "" +
	"\n" +
	"\x19coakka/v2/transport.proto\x12\x13coakka.v2.transport\"\x92\x06\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x19\n" +
	"\breply_to\x18\x05 \x01(\tR\areplyTo\x124\n" +
	"\x04kind\x18\x06 \x01(\x0e2 .coakka.v2.transport.MessageKindR\x04kind\x12\x17\n" +
	"\aone_way\x18\a \x01(\bR\x06oneWay\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x05R\ttimeoutMs\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12D\n" +
	"\aheaders\x18\n" +
	" \x03(\v2*.coakka.v2.transport.Envelope.HeadersEntryR\aheaders\x12;\n" +
	"\x06status\x18\v \x01(\x0e2#.coakka.v2.transport.BusinessStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\f \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12F\n" +
	"\rdelivery_hint\x18\x0e \x01(\x0e2!.coakka.v2.transport.DeliveryHintR\fdeliveryHint\x12!\n" +
	"\fmessage_type\x18\x0f \x01(\tR\vmessageType\x124\n" +
	"\x16payload_schema_version\x18\x10 \x01(\rR\x14payloadSchemaVersion\x12I\n" +
	"\x0epayload_format\x18\x11 \x01(\x0e2\".coakka.v2.transport.PayloadFormatR\rpayloadFormat\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\n" +
	"Deadletter\x12J\n" +
	"\x11original_envelope\x18\x01 \x01(\v2\x1d.coakka.v2.transport.EnvelopeR\x10originalEnvelope\x12=\n" +
	"\x06reason\x18\x02 \x01(\x0e2%.coakka.v2.transport.DeadletterReasonR\x06reason\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12+\n" +
	"\x11active_generation\x18\x04 \x01(\x04R\x10activeGeneration\x12#\n" +
	"\rresolved_host\x18\x05 \x01(\tR\fresolvedHost\x12#\n" +
	"\rresolved_port\x18\x06 \x01(\rR\fresolvedPort*x\n" +
	"\vMessageKind\x12\x1c\n" +
	"\x18MESSAGE_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MESSAGE_KIND_REQUEST\x10\x01\x12\x19\n" +
	"\x15MESSAGE_KIND_RESPONSE\x10\x02\x12\x16\n" +
	"\x12MESSAGE_KIND_EVENT\x10\x03*d\n" +
	"\x0eBusinessStatus\x12\x1f\n" +
	"\x1bBUSINESS_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BUSINESS_STATUS_OK\x10\x01\x12\x19\n" +
	"\x15BUSINESS_STATUS_ERROR\x10\x02*\xb2\x01\n" +
	"\fDeliveryHint\x12\x1d\n" +
	"\x19DELIVERY_HINT_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cDELIVERY_HINT_ROUTER_DEFAULT\x10\x01\x12\x1e\n" +
	"\x1aDELIVERY_HINT_PREFER_LOCAL\x10\x02\x12\x1f\n" +
	"\x1bDELIVERY_HINT_REQUIRE_LOCAL\x10\x03\x12 \n" +
	"\x1cDELIVERY_HINT_REQUIRE_REMOTE\x10\x04*\xd6\x01\n" +
	"\rPayloadFormat\x12\x1e\n" +
	"\x1aPAYLOAD_FORMAT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PAYLOAD_FORMAT_JSON\x10\x01\x12\x1b\n" +
	"\x17PAYLOAD_FORMAT_PROTOBUF\x10\x02\x12\x19\n" +
	"\x15PAYLOAD_FORMAT_THRIFT\x10\x03\x12\x1a\n" +
	"\x16PAYLOAD_FORMAT_MSGPACK\x10\x04\x12\x1d\n" +
	"\x19PAYLOAD_FORMAT_PLAIN_TEXT\x10\x05\x12\x19\n" +
	"\x15PAYLOAD_FORMAT_BINARY\x10\x06*\xfc\x04\n" +
	"\x10DeadletterReason\x12!\n" +
	"\x1dDEADLETTER_REASON_UNSPECIFIED\x10\x00\x12(\n" +
	"$DEADLETTER_REASON_NO_ACTIVE_SNAPSHOT\x10\x01\x12 \n" +
	"\x1cDEADLETTER_REASON_ROUTE_MISS\x10\x02\x12)\n" +
	"%DEADLETTER_REASON_NO_RESPONSIBLE_HOST\x10\x03\x12$\n" +
	" DEADLETTER_REASON_QUEUE_REJECTED\x10\x04\x12*\n" +
	"&DEADLETTER_REASON_LOCAL_HANDOFF_FAILED\x10\x05\x12%\n" +
	"!DEADLETTER_REASON_DELIVERY_FAILED\x10\x06\x12%\n" +
	"!DEADLETTER_REASON_CAF_SEND_FAILED\x10\a\x12%\n" +
	"!DEADLETTER_REASON_RUNTIME_STOPPED\x10\b\x12&\n" +
	"\"DEADLETTER_REASON_INVALID_ENVELOPE\x10\t\x12*\n" +
	"&DEADLETTER_REASON_ENDPOINT_UNAVAILABLE\x10\n" +
	"\x12*\n" +
	"&DEADLETTER_REASON_REMOTE_REPLY_TIMEOUT\x10\v\x12'\n" +
	"#DEADLETTER_REASON_LOCALITY_MISMATCH\x10\f\x12-\n" +
	")DEADLETTER_REASON_EXPIRED_BEFORE_DELIVERY\x10\r\x12/\n" +
	"+DEADLETTER_REASON_ONE_WAY_DROPPED_BY_POLICY\x10\x0eBX\n" +
	"\x13coakka.v2.transportP\x01Z?github.com/phuong-tran/coakka-runtime-go/internal/wirepb;wirepbb\x06proto3"

var (
	file_coakka_v2_transport_proto_rawDescOnce sync.Once
	file_coakka_v2_transport_proto_rawDescData []byte
)

func file_coakka_v2_transport_proto_rawDescGZIP() []byte {
	file_coakka_v2_transport_proto_rawDescOnce.Do(func() {
		file_coakka_v2_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coakka_v2_transport_proto_rawDesc), len(file_coakka_v2_transport_proto_rawDesc)))
	})
	return file_coakka_v2_transport_proto_rawDescData
}

var file_coakka_v2_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_coakka_v2_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_coakka_v2_transport_proto_goTypes = []any{
	(MessageKind)(0),      // 0: coakka.v2.transport.MessageKind
	(BusinessStatus)(0),   // 1: coakka.v2.transport.BusinessStatus
	(DeliveryHint)(0),     // 2: coakka.v2.transport.DeliveryHint
	(PayloadFormat)(0),    // 3: coakka.v2.transport.PayloadFormat
	(DeadletterReason)(0), // 4: coakka.v2.transport.DeadletterReason
	(*Envelope)(nil),      // 5: coakka.v2.transport.Envelope
	(*Deadletter)(nil),    // 6: coakka.v2.transport.Deadletter
	nil,                   // 7: coakka.v2.transport.Envelope.HeadersEntry
}
var file_coakka_v2_transport_proto_depIdxs = []int32{
	0, // 0: coakka.v2.transport.Envelope.kind:type_name -> coakka.v2.transport.MessageKind
	7, // 1: coakka.v2.transport.Envelope.headers:type_name -> coakka.v2.transport.Envelope.HeadersEntry
	1, // 2: coakka.v2.transport.Envelope.status:type_name -> coakka.v2.transport.BusinessStatus
	2, // 3: coakka.v2.transport.Envelope.delivery_hint:type_name -> coakka.v2.transport.DeliveryHint
	3, // 4: coakka.v2.transport.Envelope.payload_format:type_name -> coakka.v2.transport.PayloadFormat
	5, // 5: coakka.v2.transport.Deadletter.original_envelope:type_name -> coakka.v2.transport.Envelope
	4, // 6: coakka.v2.transport.Deadletter.reason:type_name -> coakka.v2.transport.DeadletterReason
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_coakka_v2_transport_proto_init() }
func file_coakka_v2_transport_proto_init() {
	if File_coakka_v2_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coakka_v2_transport_proto_rawDesc), len(file_coakka_v2_transport_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coakka_v2_transport_proto_goTypes,
		DependencyIndexes: file_coakka_v2_transport_proto_depIdxs,
		EnumInfos:         file_coakka_v2_transport_proto_enumTypes,
		MessageInfos:      file_coakka_v2_transport_proto_msgTypes,
	}.Build()
	File_coakka_v2_transport_proto = out.File
	file_coakka_v2_transport_proto_goTypes = nil
	file_coakka_v2_transport_proto_depIdxs = nil
}
